### ISSUE TITLE
Vysvětlení kódu v suggestion controleru 

### ISSUE THREAD

**Issue by st49617** [st49617/Voting-system#19]
Jak v Controleru fungují metody

**addSuggestion** a **deleteSuggestion**

spíše jak funguje předávání parametrů do metod.
To se jako za jeden parametr zadá celá entita nebo jak to potom funguje při volání API

**Comment by Burdis28** [comment]
Ještě jsem změnil anotaci na RequestBody. Jako parametr se v postu pošle JSON objekt s definovanými atributy podle DTO Suggestion (bude vytvořena). Spring MVC už si to pak mapuje sám a případně provádí i typovou konverzi.

**Comment by st49617** [comment]
Až bude opraveno na RequestBody a bude vytvořen pull reguest tak potom se bude zavírat issue.
