### ISSUE TITLE
Dotaz na User/UserDto

### ISSUE THREAD

**Issue by ptnavratil** [st49617/Voting-system#29]
Pracuju na uživatelích (zastupitelech) a Entita zatím vypadá takto:

<pre>
@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    private String firstName;
    @NotNull
    private String lastName;
    @NotNull
    @Column(unique = true)
    private String email;
    @NotNull
    private String passwordHash;
}
</pre>

Co si o tom myslíte?
_Moje myšlenka je taková že bude přihlašovat (až se to bude nějak dělat) pomocí email+heslo._

**Ale hlavně se chci zeptat co by mělo obsahovat UserDto?**

**Comment by st49617** [comment]
Entita je asi v pohodě. Do dto mě nic nenapadá. Takže dto zatím nebude potřeba. Je potřeba vymyslet jak Teda budeme dělat přihlašování. Od toho se bude vyvíjet další postup. Udělám issue jenom na analýzu přihlašování v springu.

**Comment by ptnavratil** [comment]
Já jsem právě koukal do tvýho VotingDto a tam máš:
<pre>
//    TODO: Dodělat až bude
//    private UserDto user;
</pre>
Tak jak to udělat abys to mohl využívat.

**Comment by Burdis28** [comment]
Dto bude stejné akorát bez hesla a možná i bez emailu.

**Comment by st49617** [comment]
Na to sem pozapomel v dto se data nebudou přidávat jako jinde ale bude se zde  odebírat minimálně to heslo

**Comment by ptnavratil** [comment]
Vytvořeno issue #39.
