### ISSUE TITLE
Vytvoření TagService

### ISSUE THREAD

**Issue by st49617** [st49617/Voting-system#3]
Pod tímto úkolem se rozumí:vytvoření Service, entyty, Dao, controlleru. Výsledný controller bude poskytovat jen. Rest api rozhraní pro vkládání odebírání poskytování daného prvku a seznamu všech prvků

**Comment by st46619** [comment]
@seri300 Pokud s tim potrebujes pomoci, bylo by vhodne rozjet nejakou diskuzi. Milestone byl jedenact dni zpatky a bez zakladnich API se nam projekt stopne pred business logikou, coz znamena zitra.

**Comment by st46619** [comment]
Soucasti pullu #35
