### ISSUE TITLE
Špatné nastavení DB připojení

### ISSUE THREAD

**Issue by ptnavratil** [st49617/Voting-system#30]
Neukládají se správně všechny české znaky.

Řešení:
do `application.properties` k parametrům na `spring.datasource.url` přidat ještě:
`useUnicode=yes&characterEncoding=UTF-8`

Zkoušel jsem to při přidávání uživatelů a je to Ok.

**Comment by ptnavratil** [comment]
Přidal jsem tam ty parametry ve svém Pull requestu toho UserService.

**Comment by st49617** [comment]
Můžes to kdyztak opravit, celý den nebudu doma

**Comment by st46619** [comment]
Vyreseno v pullu od @ptnavratil .
