### ISSUE TITLE
Sprava Meeting vs. Suggestion

### ISSUE THREAD

**Issue by st46619** [st49617/Voting-system#34]
Meli bychom se domluvit, zda budeme pristupovat pres suggestions k meetingum, nebo naopak. Nebo, v pripade oboustranneho pristupu, pak bude potreba vytvorit kontejnery bez zavislosti, se kterymi bude pracovat protejsek misto stavajicich DTO.
Momentalne je totiz situace takova, ze MeetingDto ma svuj seznam SuggestionDto, ktere obsahuji pochopitelne zase odkazy na Meetingy. Pokud je @Burdis28 zreviduje na prenos pomoci DTO, vznikne cyklicka zavislost.

**Comment by st49617** [comment]
Chápu. Probrereme v pondělí

**Comment by ptnavratil** [comment]
Vytvořeno issue #42.
