### ISSUE TITLE
Inicializace základní frontend aplikace

### ISSUE THREAD

**Issue by ptnavratil** [st49617/Voting-system#43]

**Comment by st46619** [comment]
Tohle je docela velka vec a asi bys na ni nemel delat jenom ty.
Doporucoval bych rozhazet dalsi issues, protoze krom pana @seri300, ktery stale nedotlacil ani to API, co melo byt hotove pred tydnem, asi nikdo nema v tomto projektu do ceho pichnout a ty zatim delas sam na zasadnim a velkem ukolu.
