### ISSUE TITLE
Thymeleaf rozhrani pro User

### ISSUE THREAD

**Issue by st46619** [st49617/Voting-system#58]
Melo by obsahovat formulare pro vytvoreni, zmenu a smazani uzivatele.

**Comment by st46619** [comment]
Az nekdo zamerguje ty microservices, tak to asi bude potreba opravit. :D

**Comment by ptnavratil** [comment]
Mám několik dotazů:
1. Jak má fungovat změna uživatele, co má umožňovat změnit? Jenom jméno, příjmení, nebo i email a heslo? Pokud heslo, tak jak - při změně hesla by to chtělo zadat to starý, ale to ten člověk nebude vědět?(Tuto správu bude používat nějakej správce?)...
2. Jak bude probíhat Smazání uživatele, to se normálně smaže a konec? Neměli by se nějakým způsobem smazat všechny Hlasování tohoto uživatele? Nebo jakým způsobem se to bude řešit? (Každý Vote má userId)

Jak to vidíte @st46619, @st49617?

**Comment by st46619** [comment]
Koukal jsem do zadani a konkretne spravu uzivatelu jsem tam nezahledl, takze bych se tim nejak vyrazne nezdrzoval. Osobne jsem pro to, predpokladat, ze ucet vytvori a spravuje zastupiteli nejaky spravce.
Zmena hesla je samozrejme celkem zasadni, tuto moznost by asi mel mit, ale to bychom tam museli rozchodit nejakou kontrolu pristupu. Nevim, zda to tam mas. Dalo by se to zjednodusit na generovani hesel. Zapomnel? -> Vygenerovat nahodny string, zobrazit a zadat ho do DB. Samozrejme bezpecnostne je to prasarna, ale tohle je mimo pozadovanou funkcionalitu.
Na smazani bych, kvuli historii z jednani a tak, vubec nepristupoval. Spis tam mel byt nejaky priznak, zda je uzivatel aktualni a pokud ne, nemohl by se prihlasit. Ale to uz ted menit nemuzem.

V kostce, pokud v zadani neni sprava uzivatelu (a ja ji tam nezahledl), klidne bych to nechal na pridavani uzivatele. To je jedine, co pro beh aplikace potrebujem.
