### ISSUE TITLE
Zjištění jak funguje M:N relace v entitách ve springu

### ISSUE THREAD

**Issue by st49617** [st49617/Voting-system#7]

**Comment by ptnavratil** [comment]
Myslím, že tento článek by nám s tím mohl pomoct.
[M:N relace v JPA](https://www.baeldung.com/jpa-many-to-many)

**Comment by st49617** [comment]
Stejně asi nebudeme dělat přes M:N relaci. Máme tam entitu která bude ve valstní mikroservice.
