### ISSUE TITLE
Oprava suggestion API

### ISSUE THREAD

**Issue by st49617** [st49617/Voting-system#72]
Přes API nejde vkládat sugestions, které v contentu obsahují "ě" (možná i jiné).

**Comment by ptnavratil** [comment]
Co to hlásí za chybu? Dneska něco zkoušel @st49617 ve škole a taky s tím contentem měl nějaký problém, ale pak se to nějak spravilo.

**Comment by ptnavratil** [comment]
Jo sorry to si vytvořil ty, já to špatně pochopil...

**Comment by Burdis28** [comment]
Zkusil jsem replikovat problém, ovšem neúspěšně. Tzn. že to není bug a vkládat se Suggestion dá i s českými znaky v contentu. Viz [screen.](https://imgur.com/a/MAOhfvU)

Vytvořená suggestion, získaná přes api get-all:
id | 3
content | "ě"
meetingId | 123
accepted | "NEROZHODNUTO"
